const friendsNum = 7
const meatSentences = 3
const maxPokemonNum = 1000
const gifAPIKey = 'wHBlvCmiGEcd63wfdckwnpnprv7voTse'
const personAPI = 'https://randomuser.me/api/?inc=gender,name,email,location,picture&results=1'
const friendsAPI = `https://randomuser.me/api/?inc=gender,name&results=${friendsNum}`
const quoteAPI = 'https://api.kanye.rest'
const meatAPI = `https://baconipsum.com/api/?type=all-meat&sentences=${meatSentences}`
const pokemonAPI = `https://pokeapi.co/api/v2/pokemon/`
const gifAPI = `https://api.giphy.com/v1/gifs/search?api_key=${gifAPIKey}&limit=1&offset=0&rating=g&lang=en&bundle=messaging_non_clips&q=`